version: "3.7"

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./deploy/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    restart: unless-stopped

  db:
    container_name: db
    build:
      context: ./
      dockerfile: ./deploy/postgres/Dockerfile
    command:
      - "postgres"
      - "-c"
      - "max_connections=10"
      - "-c"
      - "shared_buffers=500MB"
      - "-c"
      - "effective_cache_size=2GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - ./deploy/postgres/pg-data/init-database:/docker-entrypoint-initdb.d
      - ./deploy/postgres/pg-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Vladivostok
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: electronly_main
      PGDATA: "/var/lib/postgresql/data/pgdata"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d electronly_main"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4G
    
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./deploy/app/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - nginx
      - db

networks:
  default:
    name: api-network
    external: true